### PR TITLE
Handle Hubtel Initiation for long-codes

### PR DESCRIPTION
**Pull request by yono38**
Hey @habbes - been using this internally for about 6 months now but wanted to contribute it back to the library.

This allows USSD users on Hubtel to send us an initial long-code that will send them directly to a route. It's different from the AT handling because Hubtel uses "Initiation" vs "Response" states instead of sending the full route as asterisk-joined text like AT does.

Let me know any questions or comments.

### CODE REVIEW

**Comment by habbes** [comment]
Thanks @yono38 for this contribution.
I'm going to merge it.

**Comment by habbes** [comment]
I think the library could use a re-design eventually to separate out provider-specific code from the core part of the library. The core component could take care of the state machine, and providers could be implemented separately, based on a common interface. This would also make it easier to add support for other providers as well. Maybe this could be a discussion for v2. But I don't know how many people use the library and whether such an overhaul/rewrite would be worth the investment.

**Comment by shobande-femi** [comment]
hey man, been working on a Kotlin DSL similar to your library. I could use some feedback

https://github.com/shobande-femi/menufactory

**Comment by habbes** [comment]
Thanks @shobande-femi, I will definitely give it a look. Where would be a good place for me to share my feedback if I have any?

**Comment by shobande-femi** [comment]
Hey, here's my email address: osshobey@gmail.com

**Pull request merged**
